version: "3.1"

services:
  authentication:
    # A service handling authentication and JWT generation.
    build: .
    environment:
      SESSION_COOKIE_NAME: custom-analytics
      GITHUB_CLIENT_ID: MyClientID
      GITHUB_CLIENT_SECRET: MySecret
      GITHUB_ORG_IS_ADMIN: MyGitHubOrg
      JWT_SECRET: jwtsecret
      COOKIE_SIGNING: cookiesign
      AUTH_STRATEGY: local
    ports:
      - "3000:3000"